from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

ROOT_DIR = Path(__file__).resolve().parents[3]
DATA_DIR = ROOT_DIR / "data"
IMAGES_DIR = DATA_DIR / "images"
META_DIR = DATA_DIR / "meta"
SAMPLING_STATE_DIR = META_DIR / "sampling"
OSM_EXPORT_DIR = DATA_DIR / "osm"
ARCHIVE_DIR = DATA_DIR / "archives"
OSM_CLASSES_PATH = Path(__file__).resolve().with_name("osm_classes.json")

DEFAULT_PROJECT_NAME = os.getenv("SLY_PROJECT_NAME", "satellite_osm_downloads")
DEFAULT_DATASET_NAME = os.getenv("SLY_DATASET_NAME", "downloaded")
ANNOTATION_BATCH_SIZE = int(os.getenv("SLY_ANN_BATCH_SIZE", "200"))


def load_environment(local_env_path: Optional[Path] = None) -> None:
    """Load local and Supervisely environment files.

    :param local_env_path: Optional path to the local environment file.
    :type local_env_path: Optional[Path]
    """

    resolved_local_env = local_env_path or ROOT_DIR / "local.env"
    supervisely_env_path = Path.home() / "supervisely.env"

    if resolved_local_env.exists():
        load_dotenv(resolved_local_env)

    if supervisely_env_path.exists():
        load_dotenv(supervisely_env_path)


def ensure_data_directories() -> None:
    """Create data directories used by scripts and app runs."""

    for path in [
        DATA_DIR,
        IMAGES_DIR,
        META_DIR,
        SAMPLING_STATE_DIR,
        OSM_EXPORT_DIR,
        ARCHIVE_DIR,
    ]:
        path.mkdir(parents=True, exist_ok=True)


def build_generated_name(prefix: str) -> str:
    """Build a timestamped name for autogenerated projects or datasets.

    :param prefix: Human readable prefix.
    :type prefix: str
    :return: Generated name.
    :rtype: str
    """

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    return "{prefix}_{timestamp}".format(prefix=prefix, timestamp=timestamp)


def read_optional_int_env(name: str) -> Optional[int]:
    """Read an optional integer environment variable.

    :param name: Environment variable name.
    :type name: str
    :return: Parsed integer value or ``None`` for missing and blank values.
    :rtype: Optional[int]
    """

    raw_value = os.getenv(name)
    if raw_value is None:
        return None

    value = raw_value.strip()
    if value == "":
        return None

    return int(value)


def sanitize_filename(value: str) -> str:
    """Convert an arbitrary string to a filesystem-friendly name.

    :param value: Source string.
    :type value: str
    :return: Sanitized string.
    :rtype: str
    """

    cleaned = "".join(
        char if char.isalnum() or char in ("-", "_") else "_" for char in value.strip()
    )
    cleaned = cleaned.strip("_")
    return cleaned or "item"
